kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hostpath-provisioner
provisioner: kubevirt.io.hostpath-provisioner
parameters:
  storagePool: local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

