apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ci-pipeline
  namespace: quarkus-app-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 30Gi
