apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-artifact
spec:
  workspaces:
  - name: nexus
  params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["package"]
  resources:
    - name: source
      type: git
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      workingDir: /workspace/source
      command: ["/usr/bin/mvn"]
      args:
        - deploy
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(params.GOALS)"
