apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: push-artifact
  namespace: quarkus-app-dev
spec:
  workspaces:
  - name: nexus
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      value: deploy
    resources:
    - name: source
      type: git
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      workingDir: /workspace/source
      command: ["/usr/bin/mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(inputs.params.GOALS)"
