apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2023-02-02T20:09:27Z'
  generation: 6
  labels:
    app.kubernetes.io/instance: java-app
    app.kubernetes.io/name: java-app
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/runtime: java
    pipeline.openshift.io/runtime-version: openjdk-17-ubi8
    pipeline.openshift.io/type: kubernetes
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:operator.tekton.dev/operand-name': {}
            'f:pipeline.openshift.io/runtime': {}
            'f:pipeline.openshift.io/runtime-version': {}
            'f:pipeline.openshift.io/type': {}
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2023-02-02T20:34:38Z'
  name: java-app
  resourceVersion: '60639'
  uid: bca4c9b6-00e9-40b8-bfd6-5178f7421d9a
spec:
  params:
    - default: java-app
      name: APP_NAME
      type: string
    - default: 'https://github.com/gwsantos/openshift-quickstarts.git'
      name: GIT_REPO
      type: string
    - default: master
      name: GIT_REVISION
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/java-app/java-app'
      name: IMAGE_NAME
      type: string
    - default: undertow-servlet
      name: PATH_CONTEXT
      type: string
    - default: openjdk-17-ubi8
      name: VERSION
      type: string
    - default: 'https://quay.io/gdesouza/java-sample'
      name: QUAY_REPO_URL
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: '$(params.QUAY_REPO_URL):latest'
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: quay-robot-secret
    - name: deploy
      params:
        - name: SCRIPT
          value: oc rollout status deploy/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace
    - name: quay-robot-secret
