apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: java-pipeline
spec:
  params:
  - default: java-app
    name: APP_NAME
    type: string
  - default: https://github.com/gwsantos/openshift-quickstarts.git
    name: GIT_REPO
    type: string
  - default: master
    name: GIT_REVISION
    type: string
  - default: java-app
    name: DEPLOYMENT_NAME
    type: string
  - default: >-
        image-registry.openshift-image-registry.svc:5000/java-pipeline/java-app:latest
    name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: openjdk-17-ubi8
    name: VERSION
    type: string
  tasks:
  - name: fetch-repository
    params:
      - name: url
        value: $(params.GIT_REPO)
      - name: revision
        value: $(params.GIT_REVISION)
      - name: subdirectory
        value: ''
      - name: deleteExisting
        value: 'true'
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: workspace
  - name: build
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
      - name: SCRIPT
        value: oc start-build bc/$(params.APP_NAME)
      - name: VERSION
        value: latest
    runAfter:
    - fetch-repository
    workspaces: []
  - name: deploy
    params:
      - name: SCRIPT
        value: oc rollout status deploy/$(params.DEPLOYMENT_NAME)
    runAfter:
      - build
    taskRef:
      kind: ClusterTask
      name: openshift-client
  workspaces:
  - name: workspace
