apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ci-pipeline
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: pipeline-trigger-binding
        - kind: ClusterTriggerBinding
          ref: github-push
      name: java-pipeline
      template:
        ref: ci-pipeline-trigger
