apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ci-pipeline-trigger
  labels:
    app.kubernetes.io/instance: java-pipeline-triggers
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-pipeline-
      spec:
        params:
          - name: APP_NAME
            value: java-app
          - name: GIT_REPO
            value: 'https://github.com/gwsantos/openshift-quickstarts.git'
          - name: GIT_REVISION
            value: master
          - name: IMAGE_NAME
            value: >-
              image-registry.openshift-image-registry.svc:5000/java-pipeline/java-app
          - name: PATH_CONTEXT
            value: .
          - name: VERSION
            value: openjdk-17-ubi8
        pipelineRef:
          name: java-pipeline
        resources: []
        status: null
        workspaces:
          - name: workspace