apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argo-application
spec:
    destination:
        namespace: test
        server: 'https://kubernetes.default.svc'
    source:
        path: k8s/overlays/dev
        repoURL: 'https://github.com/gwsantos/openshift-pipelines.git'
        targetRevision: main
    project: default
    syncPolicy:
        automated:
        prune: true
        selfHeal: true
